# docker-compose.yml

version: '3.9'

services:
  feeds-lister:
    image: jackie264/feeds-lister:latest

    container_name: feeds-lister-container
    restart: unless-stopped
    network_mode: host

    volumes:
      - /path/to/your/data:/feeds_data

    environment:
      - TZ=Asia/Shanghai
      - DOMAIN_FOOTER_INFO_JSON='{"sh-mtgc.com":{"icp_text":"沪ICP备2024068389号-2","icp_url":"https://beian.miit.gov.cn/","mps_text":"","mps_url":"https://beian.mps.gov.cn/#/query/webSearch?code=_sh-mtgc.com_代码"},"onenas.space":{"icp_text":"沪ICP备2025124234号-2","icp_url":"https://beian.miit.gov.cn/","mps_text":"沪公网安备31011002007335号","mps_url":"https://beian.mps.gov.cn/#/query/webSearch?code=31011002007335"}}'
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

    labels:
      - "watchtower.enable=true"

    # COMMAND (CMD) 是在 Dockerfile 中定义的 (CMD ["python3", "list_server.py"])
    # 如果您想在这里覆盖 Dockerfile 中的 COMMAND，可以使用 'command' 指令
    # command: ["python3", "list_server.py"]
