# docker-compose.yml

version: '3.9'

services:
  feeds-lister:
    image: jackie264/feeds-lister:latest

    container_name: feeds-lister-container
    restart: unless-stopped
    network_mode: host

    volumes:
      - /path/to/your/data:/feeds_data

    environment:
      - TZ=Asia/Shanghai
      - DOMAIN_FOOTER_INFO_JSON={
          "example1.com":{
            "icp_text":"xxxx",
            "icp_url":"https://beian.miit.gov.cn/",
            "mps_text":"",
            "mps_url":"https://beian.mps.gov.cn/#/query/webSearch?code=_example1.com_代码"
          },
          "example2.com":{
            "icp_text":"yyyy",
            "icp_url":"https://beian.miit.gov.cn/",
            "mps_text":"zzzz",
            "mps_url":"https://beian.mps.gov.cn/#/query/webSearch?code=1234567890"
          }
        }
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

    labels:
      - "watchtower.enable=true"

    # COMMAND (CMD) 是在 Dockerfile 中定义的 (CMD ["python3", "list_server.py"])
    # 如果您想在这里覆盖 Dockerfile 中的 COMMAND，可以使用 'command' 指令
    # command: ["python3", "list_server.py"]
